In [1]:
import shap

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=6, n_informative=2,random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X, y)

/home/jarek/projects/shap/venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RandomForestRegressor(max_depth=2, random_state=0)

In [2]:
from shap.explainers.pytree import *
texp = TreeExplainer(regr)

In [3]:
texp.shap_values(X[:1])

oryginalna implemenacja shap_values
other model type
using slow python treeshap


array([[ 1.06666101e+02,  1.21872088e+00,  0.00000000e+00,
         0.00000000e+00, -4.14870751e-02,  0.00000000e+00,
         3.10616114e+00]])

In [4]:
for i in range(0, X.shape[1]):
    print(texp.brute_shap(X[0], i))

[106.66610146]
[1.21872088]
[0.]
[0.]
[-0.04148708]
[0.]


In [5]:
for i in range(0, X.shape[1]):
    print(texp.brute_banz(X[0], i))

[106.66610146]
[1.21872088]
[0.]
[0.]
[-0.04148708]
[0.]


In [6]:
texp.banz_values(X[:1])

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
using numba py banz
dwa wymiary


[[106.6661014629383, 1.2187208754477359, 0.0, 0.0, -0.04148707509645545, 0.0]]

In [7]:
from shap import TreeExplainer as TreeCext
texp_cext = TreeCext(regr)

texp_cext.shap_values(X[0], banz=True, check_additivity=False)

ile drzew cext? 100
using treeshap and cext
banz = True
using cext banz


array([ 1.06666101e+02,  1.21872088e+00,  0.00000000e+00,  0.00000000e+00,
       -4.14870751e-02,  0.00000000e+00])

In [8]:
texp_cext.shap_values(X[0], banz=False)

using treeshap and cext
banz = False
here37
using dense_Tree_pred


array([ 1.06666101e+02,  1.21872088e+00,  0.00000000e+00,  0.00000000e+00,
       -4.14870751e-02,  0.00000000e+00])

In [9]:
X[0]


array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788])

In [10]:
X.iloc[0]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'