In [2]:
import shap

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=4, n_informative=2,random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=2)
regr.fit(X, y)

/home/jarek/projects/shap/venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RandomForestRegressor(max_depth=2, n_estimators=2, random_state=0)

In [26]:
from shap.explainers.pytree import *
texp = TreeExplainer(regr)
texp.shap_values(X[:1])

oryginalna implemenacja shap_values
other model type
using slow python treeshap


array([[22.48506813, 44.11025254,  0.        ,  0.        , -2.96816224]])

In [16]:
texp.brute_shap(X[0], 0)

array([24.28813233])

In [15]:
texp.brute_banz(X[0], 0)

array([24.28813233])

In [17]:
texp.banz_values(X[0])

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
{'children_default': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_left': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_right': array([ 4,  3, -1, -1,  6, -1, -1], dtype=int32),
 'features': array([ 1,  0, -2, -2,  0, -2, -2], dtype=int32),
 'max_depth': 2,
 'node_sample_weight': array([100.,  64.,  37.,  27.,  36.,  26.,  10.]),
 'thresholds': array([ 0.10953759,  0.43508366, -2.        , -2.        ,  0.76641414,
       -2.        , -2.        ]),
 'values': array([[ -2.0710816 ],
       [-19.7675118 ],
       [-34.58580269],
       [  0.53903498],
       [ 29.38923875],
       [ 19.32700042],
       [ 55.55105841]])}
jeden wymiar
ile drzew? 1
betas orig:
[1.         0.32       0.0925     0.2275     0.68       0.24555556
 0.43444444 1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.    

[24.288132332460496, 33.33400767387868, 0.0, 0.0]

In [8]:
from shap import TreeExplainer as TreeCext
texp_cext = TreeCext(regr)

texp_cext.shap_values(X[0], banz=True, check_additivity=False)

using treeshap and cext
tree:
{'base_offset': array([0.]),
 'cat_feature_indices': None,
 'children_default': array([[ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1]], dtype=int32),
 'children_left': array([[ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1]], dtype=int32),
 'children_right': array([[ 4,  3, -1, -1,  6, -1, -1],
       [ 4,  3, -1, -1,  6, -1, -1]], dtype=int32),
 'data': None,
 'data_missing': None,
 'features': array([[ 1,  0, -2, -2,  0, -2, -2],
       [ 1,  1, -2, -2,  0, -2, -2]], dtype=int32),
 'fully_defined_weighting': True,
 'input_dtype': <class 'numpy.float32'>,
 'internal_dtype': <class 'numpy.float64'>,
 'max_depth': 2,
 'model_output': 'raw',
 'model_type': 'internal',
 'node_sample_weight': array([[100.,  64.,  37.,  27.,  36.,  26.,  10.],
       [100.,  67.,  19.,  48.,  33.,  20.,  13.]]),
 'num_nodes': array([7, 7], dtype=int32),
 'num_outputs': 1,
 'num_stacked_models': 1,
 'objective': None,
 'thresholds': array([[ 0

array([11.24253407, 17.73910925,  0.        ,  0.        ])

dense tree banz 2
banz 1
22.4851
35.4782
0
0
banz 2
dense tree banz 3


In [25]:
texp_cext.shap_values(X[0], banz=False)

using treeshap and cext
tree:
{'base_offset': array([0.]),
 'cat_feature_indices': None,
 'children_default': array([[ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1]], dtype=int32),
 'children_left': array([[ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1]], dtype=int32),
 'children_right': array([[ 4,  3, -1, -1,  6, -1, -1],
       [ 4,  3, -1, -1,  6, -1, -1]], dtype=int32),
 'data': None,
 'data_missing': None,
 'features': array([[ 1,  0, -2, -2,  0, -2, -2],
       [ 1,  1, -2, -2,  0, -2, -2]], dtype=int32),
 'fully_defined_weighting': True,
 'input_dtype': <class 'numpy.float32'>,
 'internal_dtype': <class 'numpy.float64'>,
 'max_depth': 2,
 'model_output': 'raw',
 'model_type': 'internal',
 'node_sample_weight': array([[100.,  64.,  37.,  27.,  36.,  26.,  10.],
       [100.,  67.,  19.,  48.,  33.,  20.,  13.]]),
 'num_nodes': array([7, 7], dtype=int32),
 'num_outputs': 1,
 'num_stacked_models': 1,
 'objective': None,
 'thresholds': array([[ 0

array([22.48506813, 44.11025254,  0.        ,  0.        ])

In [22]:
X[0]


array([1.76405235, 0.40015721, 0.97873798, 2.2408932 ])

In [24]:
X.iloc[0]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'