In [1]:
import shap

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=6, n_informative=2,random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X, y)

/home/jarek/projects/shap/venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RandomForestRegressor(max_depth=2, random_state=0)

In [11]:
from shap.explainers.pytree import *
texp = TreeExplainer(regr)

In [3]:
texp.shap_values(X[:1])

oryginalna implemenacja shap_values
other model type
using slow python treeshap


array([[ 1.06666101e+02,  1.21872088e+00,  0.00000000e+00,
         0.00000000e+00, -4.14870751e-02,  0.00000000e+00,
         3.10616114e+00]])

In [4]:
for i in range(0, X.shape[1]):
    print(texp.brute_shap(X[0], i))

[106.66610146]
[1.21872088]
[0.]
[0.]
[-0.04148708]
[0.]


In [5]:
for i in range(0, X.shape[1]):
    print(texp.brute_banz(X[0], i))

[106.66610146]
[1.21872088]
[0.]
[0.]
[-0.04148708]
[0.]


In [6]:
texp.banz_values(X[:1])

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
{'children_default': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_left': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_right': array([ 4,  3, -1, -1,  6, -1, -1], dtype=int32),
 'features': array([ 0,  0, -2, -2,  0, -2, -2], dtype=int32),
 'max_depth': 2,
 'node_sample_weight': array([100.,  60.,  25.,  35.,  40.,  26.,  14.]),
 'thresholds': array([ 0.47623609, -0.74883819, -2.        , -2.        ,  1.13948375,
       -2.        , -2.        ]),
 'values': array([[  4.75668875],
       [-39.54852605],
       [-73.59966521],
       [-15.22628379],
       [ 71.21451095],
       [ 52.0915725 ],
       [106.72853949]])}
dwa wymiary
ile drzew? 100
betas orig:
[1.   0.21 0.05 0.16 0.79 0.24 0.55 1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1

[[106.6661014629383, 1.2187208754477359, 0.0, 0.0, -0.04148707509645545, 0.0]]

In [7]:
from shap import TreeExplainer as TreeCext
texp_cext = TreeCext(regr)

texp_cext.shap_values(X[0], banz=True, check_additivity=False)

using treeshap and cext
tree:
{'base_offset': array([0.]),
 'cat_feature_indices': None,
 'children_default': array([[ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
  

array([ 0.08470799,  0.01218721,  0.        ,  0.        , -0.00041487,
        0.        ])

In [8]:
texp_cext.shap_values(X[0], banz=False)

using treeshap and cext
tree:
{'base_offset': array([0.]),
 'cat_feature_indices': None,
 'children_default': array([[ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
       [ 1,  2, -1, -1,  5, -1, -1],
  

array([ 1.06666101e+02,  1.21872088e+00,  0.00000000e+00,  0.00000000e+00,
       -4.14870751e-02,  0.00000000e+00])

In [9]:
X[0]


array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788])

In [10]:
X.iloc[0]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'