In [1]:
import shap

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

X, y = make_regression(n_features=6, n_informative=2,random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X, y)

RandomForestRegressor(max_depth=2, random_state=0)

In [2]:
from shap.explainers.pytree import *
texp = TreeExplainer(regr)
texp.banz_values(X[:1])

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
{'children_default': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_left': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_right': array([ 4,  3, -1, -1,  6, -1, -1], dtype=int32),
 'features': array([ 0,  0, -2, -2,  0, -2, -2], dtype=int32),
 'max_depth': 2,
 'node_sample_weight': array([100.,  60.,  25.,  35.,  40.,  26.,  14.]),
 'thresholds': array([ 0.47623609, -0.74883819, -2.        , -2.        ,  1.13948375,
       -2.        , -2.        ]),
 'values': array([[  4.75668875],
       [-39.54852605],
       [-73.59966521],
       [-15.22628379],
       [ 71.21451095],
       [ 52.0915725 ],
       [106.72853949]])}
dwa wymiary
ile drzew? 1
betas: 0.125
values: [-73.59966521]
betas: 0.17500000000000002
values: [-15.22628379]
S[lewy]: -9.199958151631254
S[prawy]: -2.664599662837922
nowy S[1]: -11.864557814469176
betas: 0.13
values: [52.0915725]
betas: 0.5700000000000001
value

[[101.97185074248242, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [3]:
texp.shap_values(X[:1])

oryginalna implemenacja shap_values
other model type
using slow python treeshap


array([[101.97185074,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   4.75668875]])

In [4]:
from shap import TreeExplainer as TreeCext
texp_cext = TreeCext(regr)
line = np.asarray(X[:1])

res_cext_banz = texp_cext.shap_values(line, banz=True, check_additivity=False)

{'children_default': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_left': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_right': array([ 4,  3, -1, -1,  6, -1, -1], dtype=int32),
 'features': array([ 0,  0, -2, -2,  0, -2, -2], dtype=int32),
 'max_depth': 2,
 'node_sample_weight': array([100.,  60.,  25.,  35.,  40.,  26.,  14.]),
 'thresholds': array([ 0.47623609, -0.74883819, -2.        , -2.        ,  1.13948375,
       -2.        , -2.        ]),
 'values': array([[ 0.04756689],
       [-0.39548526],
       [-0.73599665],
       [-0.15226284],
       [ 0.71214511],
       [ 0.52091572],
       [ 1.06728539]])}
using treeshap and cext
zaczynamy!


In [5]:
res_cext_shap = texp_cext.shap_values(line, banz=False)

using treeshap and cext
here37
using dense_Tree_pred


In [6]:
res_cext_shap

array([[ 1.06666101e+02,  1.21872088e+00,  0.00000000e+00,
         0.00000000e+00, -4.14870751e-02,  0.00000000e+00]])

In [7]:
res_cext_banz

array([[0., 0., 0., 0., 0., 0.]])

In [8]:
X,y = shap.datasets.boston()
max_depth=2  # bylo 10
model = RandomForestRegressor(max_depth=max_depth, random_state=0)
model.fit(X, y)

Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    datase

RandomForestRegressor(max_depth=2, random_state=0)

In [9]:
np.asarray(X[:1])

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [10]:
texp_cext = TreeCext(model)
line = np.asarray(X[:1])

{'children_default': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_left': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_right': array([ 4,  3, -1, -1,  6, -1, -1], dtype=int32),
 'features': array([12,  5, -2, -2,  4, -2, -2], dtype=int32),
 'max_depth': 2,
 'node_sample_weight': array([506., 210., 162.,  48., 296., 204.,  92.]),
 'thresholds': array([ 9.95000029,  7.01149988, -2.        , -2.        ,  0.66349998,
       -2.        , -2.        ]),
 'values': array([[0.22312253],
       [0.29101429],
       [0.25925309],
       [0.39820833],
       [0.17495608],
       [0.19410294],
       [0.1325    ]])}


In [11]:
res_cext_shap = texp_cext.shap_values(line, banz=False)

using treeshap and cext
here37
using dense_Tree_pred


In [12]:
res_cext_banz = texp_cext.shap_values(line, banz=True, check_additivity=False)

using treeshap and cext
zaczynamy!


In [13]:
res_cext_shap

array([[ 4.26715730e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.60026738e-03, -2.23547026e+00,
         0.00000000e+00,  4.08082785e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.35142591e+00]])

In [14]:
res_cext_banz

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.43283582, 0.        , 0.        ]])

In [15]:
t = TreeExplainer(model)
t.shap_values(X[:1])

oryginalna implemenacja shap_values
other model type
using slow python treeshap


array([[ 4.26715730e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.60026738e-03, -2.23547026e+00,
         0.00000000e+00,  4.08082785e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.35142591e+00,  2.25138735e+01]])

In [16]:
t.banz_values(X[:1])

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
{'children_default': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_left': array([ 1,  2, -1, -1,  5, -1, -1], dtype=int32),
 'children_right': array([ 4,  3, -1, -1,  6, -1, -1], dtype=int32),
 'features': array([12,  5, -2, -2,  4, -2, -2], dtype=int32),
 'max_depth': 2,
 'node_sample_weight': array([506., 210., 162.,  48., 296., 204.,  92.]),
 'thresholds': array([ 9.95000029,  7.01149988, -2.        , -2.        ,  0.66349998,
       -2.        , -2.        ]),
 'values': array([[22.31225296],
       [29.10142857],
       [25.92530864],
       [39.82083333],
       [17.49560811],
       [19.41029412],
       [13.25      ]])}
dwa wymiary
ile drzew? 1
betas: 0.6266516092603048
values: [25.92530864]
betas: 0.08085827216261998
values: [39.82083333]
S[lewy]: 16.246136381063913
S[prawy]: 3.2198437794089965
nowy S[1]: 19.46598016047291
betas: 0.24703557312252966
values: [19.41029412]
betas: 0.0454

[[0.0,
  0.0,
  0.0,
  0.0,
  0.560026737967914,
  -2.2471362346724675,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  5.300165174252982]]

In [17]:
for i in range(len(line[0])):
    print(t.brute_banz(line[0], i))

[0.]
[0.]
[0.]
[0.]
[0.56002674]
[-2.24713623]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[5.30016517]


In [18]:
for i in range(len(line[0])):
    print(t.brute_shap(line[0], i))

[0.]
[0.]
[0.]
[0.]
[0.56002674]
[-2.24713623]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[5.30016517]
