In [1]:
import shap

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
import time
from timeit import default_timer as timer

X, y = make_regression(n_samples=100, n_features=8, n_informative=2,random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=6, n_estimators=50, random_state=0)
regr.fit(X, y)

/home/jarek/projects/shap/venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RandomForestRegressor(max_depth=6, n_estimators=50, random_state=0)

In [2]:
from shap.explainers.pytree import *
texp = TreeExplainer(regr)
start = timer()
res = texp.shap_values(X)
print(timer() - start)
res

6.5894478058908135


array([[ 8.51892516e+01,  5.27180562e+01, -1.45448004e-01,
        -8.38536748e-01,  8.47236449e-01,  2.76074338e+00,
        -3.49393977e-01, -8.39557788e-01, -1.33441813e+01],
       [-3.79796479e-02,  4.92815604e+01, -5.58015502e-01,
        -5.10514986e-01, -4.10727128e-01, -1.23389503e+00,
        -7.38927676e-01, -1.09915695e+00, -1.33441813e+01],
       [ 7.50555863e+01,  1.78947960e+01,  9.35836733e-01,
         2.50811211e-01, -4.72620820e-01, -1.08611086e+00,
         3.80602017e-02, -2.36159746e+00, -1.33441813e+01],
       [ 1.09021261e+02, -7.57081709e+01,  8.21035166e-01,
         8.06126027e-01,  1.32979712e+00, -1.42411151e+00,
        -3.74844414e-01,  1.13854643e-01, -1.33441813e+01],
       [-4.32137080e+01, -1.25763610e+02, -1.10835830e+00,
        -8.48283695e-01, -9.86411574e-01, -3.56544467e+00,
        -3.35408104e-01, -1.08850528e-01, -1.33441813e+01],
       [-5.05032913e+01, -9.92242357e+01, -5.99036771e-01,
        -1.96282864e+00, -1.34197510e+00,  1.313394

In [3]:
start = time.time()
res = texp.banz_values(X)
print(time.time() - start)
res

nasza implementacja banz values
dwa wymiary
4.525714874267578


array([[ 8.51215584e+01,  5.25758591e+01, -1.03515859e-01,
        -7.14884223e-01,  9.70049471e-01,  2.52457378e+00,
        -3.48612674e-01, -9.92769108e-01],
       [-5.59191039e-03,  4.94161592e+01, -5.45726064e-01,
        -5.22171763e-01, -3.91504415e-01, -1.25123921e+00,
        -7.01198005e-01, -1.04340118e+00],
       [ 7.48531944e+01,  1.75975323e+01,  7.52426858e-01,
         1.60967950e-01, -6.47395042e-01, -1.07758729e+00,
        -3.83789016e-02, -2.40926192e+00],
       [ 1.08302341e+02, -7.63277416e+01,  7.11679222e-01,
         7.44765947e-01,  1.03807423e+00, -1.72961517e+00,
        -3.78783041e-01,  2.31063676e-01],
       [-4.29900370e+01, -1.25445649e+02, -1.03469856e+00,
        -9.52047360e-01, -8.84671855e-01, -3.19415922e+00,
        -3.31645491e-01, -8.38667054e-02],
       [-5.05118399e+01, -9.92299897e+01, -5.96744478e-01,
        -1.88893563e+00, -1.27721272e+00,  1.28053210e+00,
         3.10745409e-01,  9.37356580e-01],
       [-8.50137042e+01, -1.382162

In [4]:
# start = time.time()
# res = texp.banz_values(X, jit=True)
# print(time.time() - start)
# res

In [5]:
# for i in range(len(X[0])):
#     print(texp.brute_banz(X[0], i))

In [6]:
from shap import TreeExplainer as TreeCext
texp_cext = TreeCext(regr)
line = np.asarray(X[:1])

ile drzew cext? 50


In [7]:
start = time.time()
res_cext_shap = texp_cext.shap_values(X, banz=False)
print(time.time() - start)

using treeshap and cext
banz = False
here37
using dense_Tree_pred
0.01397395133972168


In [8]:
start = time.time()
res_cext_banz = texp_cext.shap_values(X, banz=True, check_additivity=False)
print(time.time() - start)

using treeshap and cext
banz = True
using cext banz
0.02089524269104004


In [9]:
res_cext_shap

array([[ 8.51892516e+01,  5.27180562e+01, -1.45448004e-01,
        -8.38536748e-01,  8.47236449e-01,  2.76074338e+00,
        -3.49393977e-01, -8.39557788e-01],
       [-3.79796479e-02,  4.92815604e+01, -5.58015502e-01,
        -5.10514986e-01, -4.10727128e-01, -1.23389503e+00,
        -7.38927676e-01, -1.09915695e+00],
       [ 7.50555863e+01,  1.78947960e+01,  9.35836733e-01,
         2.50811211e-01, -4.72620820e-01, -1.08611086e+00,
         3.80602017e-02, -2.36159746e+00],
       [ 1.09021261e+02, -7.57081709e+01,  8.21035166e-01,
         8.06126027e-01,  1.32979712e+00, -1.42411151e+00,
        -3.74844414e-01,  1.13854643e-01],
       [-4.32137080e+01, -1.25763610e+02, -1.10835830e+00,
        -8.48283695e-01, -9.86411574e-01, -3.56544467e+00,
        -3.35408104e-01, -1.08850528e-01],
       [-5.05032913e+01, -9.92242357e+01, -5.99036771e-01,
        -1.96282864e+00, -1.34197510e+00,  1.31339464e+00,
         3.08938372e-01,  1.02697044e+00],
       [-8.53903725e+01, -1.807649

In [10]:
res_cext_banz

array([[ 8.51215584e+01,  5.25758591e+01, -1.03515859e-01,
        -7.14884223e-01,  9.70049471e-01,  2.52457378e+00,
        -3.48612674e-01, -9.92769108e-01],
       [-5.59191039e-03,  4.94161592e+01, -5.45726064e-01,
        -5.22171763e-01, -3.91504415e-01, -1.25123921e+00,
        -7.01198005e-01, -1.04340118e+00],
       [ 7.48531944e+01,  1.75975323e+01,  7.52426858e-01,
         1.60967950e-01, -6.47395042e-01, -1.07758729e+00,
        -3.83789016e-02, -2.40926192e+00],
       [ 1.08302341e+02, -7.63277416e+01,  7.11679222e-01,
         7.44765947e-01,  1.03807423e+00, -1.72961517e+00,
        -3.78783041e-01,  2.31063676e-01],
       [-4.29900370e+01, -1.25445649e+02, -1.03469856e+00,
        -9.52047360e-01, -8.84671855e-01, -3.19415922e+00,
        -3.31645491e-01, -8.38667054e-02],
       [-5.05118399e+01, -9.92299897e+01, -5.96744478e-01,
        -1.88893563e+00, -1.27721272e+00,  1.28053210e+00,
         3.10745409e-01,  9.37356580e-01],
       [-8.50137042e+01, -1.382162

In [11]:
X[:1]

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721]])

In [35]:
X,y = shap.datasets.boston()
max_depth = 16  # bylo 10
n_estimators = 1000
model = RandomForestRegressor(max_depth=max_depth, n_estimators=n_estimators, random_state=0)
model.fit(X, y)

Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    datase

RandomForestRegressor(max_depth=16, n_estimators=1000, random_state=0)

In [36]:
np.asarray(X[:1])

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [37]:
texp_cext = TreeCext(model)
line = np.asarray(X[:1])

ile drzew cext? 1000


In [38]:
start = time.time()
res_cext_shap = texp_cext.shap_values(line, banz=False)
print(time.time() - start)

using treeshap and cext
banz = False
here37
using dense_Tree_pred
0.05308961868286133


In [39]:
start = time.time()
res_cext_banz = texp_cext.shap_values(line, banz=True, check_additivity=False)
print(time.time() - start)

using treeshap and cext
banz = True
using cext banz
0.040720224380493164


In [40]:
res_cext_shap

array([[ 1.90746225e-01, -4.28840700e-03,  1.36267134e-01,
        -7.98401356e-03, -1.40445649e-01, -1.29153166e+00,
        -1.07439268e-01, -1.66133868e-01, -1.89525890e-01,
        -1.80612349e-01,  3.85660862e-01,  2.90829234e-02,
         4.55416048e+00]])

In [41]:
res_cext_banz

array([[ 2.12437897e-01,  4.38944086e-03,  1.42873465e-01,
        -8.49613297e-03, -1.34345569e-01, -1.17855036e+00,
        -8.36985241e-02, -1.38864941e-01, -1.85408533e-01,
        -1.70222314e-01,  4.11933601e-01,  3.59642916e-02,
         4.64458192e+00]])

In [ ]:
# for i in range(len(line[0])):
#     print(t.brute_banz(line[0], i))

In [ ]:
# for i in range(len(line[0])):
#     print(t.brute_shap(line[0], i))

In [ ]:
import time
start = time.time()
res_cext_shap = texp_cext.shap_values(line, banz=False)
print(time.time() - start)

In [ ]:
start = time.time()
res_cext_shap = texp_cext.shap_values(line, banz=True)
print(time.time() - start)