In [1]:
import shap

from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
import time

X, y = make_regression(n_features=6, n_informative=2,random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=6, random_state=0)
regr.fit(X, y)

/home/jarek/projects/shap/venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RandomForestRegressor(max_depth=6, random_state=0)

In [2]:
from shap.explainers.pytree import *
texp = TreeExplainer(regr)
start = time.time()
res = texp.banz_values(X[:1])
print(time.time() - start)
res

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
dwa wymiary
ile drzew? 100
betas orig:
[1.   0.21 0.05 ... 1.   1.   1.  ]
0.20140671730041504


[[103.01945724257774,
  3.265036225740643,
  0.4921122139852502,
  0.6615075755973945,
  -0.9212039149469444,
  -0.9550408724404867]]

In [3]:
start = time.time()
res = texp.shap_values(X[:1])
print(time.time() - start)
res

oryginalna implemenacja shap_values
other model type
using slow python treeshap
0.1350104808807373


array([[102.96454164,   3.25149872,   0.43725415,   0.62738619,
         -0.91736951,  -0.90073239,   3.10616114]])

In [4]:
# for i in range(len(X[0])):
#     print(texp.brute_banz(X[0], i))

In [5]:
from shap import TreeExplainer as TreeCext
texp_cext = TreeCext(regr)
line = np.asarray(X[:1])

ile drzew? 100


In [6]:
start = time.time()
res_cext_shap = texp_cext.shap_values(line, banz=False)
print(time.time() - start)

using treeshap and cext
here37
using dense_Tree_pred
0.0013186931610107422


In [7]:
start = time.time()
res_cext_banz = texp_cext.shap_values(line, banz=True, check_additivity=False)
print(time.time() - start)

using treeshap and cext
0.0008823871612548828
using cext banz


In [8]:
res_cext_shap

array([[102.96454164,   3.25149872,   0.43725415,   0.62738619,
         -0.91736951,  -0.90073239]])

In [9]:
res_cext_banz

array([[103.01945724,   3.26503623,   0.49211221,   0.66150758,
         -0.92120391,  -0.95504087]])

In [10]:
X[:1]

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788]])

In [11]:
X,y = shap.datasets.boston()
max_depth=2  # bylo 10
model = RandomForestRegressor(max_depth=max_depth, random_state=0)
model.fit(X, y)

Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    datase

RandomForestRegressor(max_depth=2, random_state=0)

In [12]:
np.asarray(X[:1])

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [13]:
texp_cext = TreeCext(model)
line = np.asarray(X[:1])

ile drzew? 100


In [14]:
res_cext_shap = texp_cext.shap_values(line, banz=False)

using treeshap and cext
here37
using dense_Tree_pred


In [15]:
res_cext_banz = texp_cext.shap_values(line, banz=True, check_additivity=False)

using treeshap and cext
using cext banz


In [16]:
res_cext_shap

array([[ 4.26715730e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.60026738e-03, -2.23547026e+00,
         0.00000000e+00,  4.08082785e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.35142591e+00]])

In [17]:
res_cext_banz

array([[ 4.26715730e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.60026738e-03, -2.23547026e+00,
         0.00000000e+00,  4.08082785e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.35142591e+00]])

In [18]:
t = TreeExplainer(model)
t.shap_values(X[:1])

oryginalna implemenacja shap_values
other model type
using slow python treeshap


array([[ 4.26715730e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.60026738e-03, -2.23547026e+00,
         0.00000000e+00,  4.08082785e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.35142591e+00,  2.25138735e+01]])

In [19]:
t.banz_values(X[:1])

nasza implementacja banz values
other model type
uzywajac pythonowego banzhafa
dwa wymiary
ile drzew? 100
betas orig:
[1.         0.59486166 0.50501276 ... 1.         1.         1.        ]


[[0.042671572987285605,
  0.0,
  0.0,
  0.0,
  0.0056002673796791405,
  -2.2354702596840053,
  0.0,
  0.004080827847568133,
  0.0,
  0.0,
  0.0,
  0.0,
  4.35142590911811]]

In [20]:
# for i in range(len(line[0])):
#     print(t.brute_banz(line[0], i))

In [21]:
# for i in range(len(line[0])):
#     print(t.brute_shap(line[0], i))

In [22]:
import time
start = time.time()
res_cext_shap = texp_cext.shap_values(line, banz=False)
print(time.time() - start)

using treeshap and cext
here37
using dense_Tree_pred
0.001960277557373047


In [23]:
start = time.time()
res_cext_shap = texp_cext.shap_values(line, banz=True)
print(time.time() - start)

using treeshap and cext
0.0027227401733398438
using cext banz
